### ISSUE TITLE
Error on first-time run

### ISSUE THREAD

**Issue by ILABUTK** [gg-innovative/larafirebase#1]
It throws this error:

`ErrorException: Array to string conversion in file .../vendor/gg-innovative/larafirebase/src/Services/Larafirebase.php on line 152`

Which leads to this line:
'Authorization' => 'Bearer ' . $this->getBearerToken()

But, it runs afterward.

**Comment by ILABUTK** [comment]
Also, I suggest revising the readme to remove the FirebaseMessage part, as it is still TBD.

**Comment by gentritabazi** [comment]
Fixed here: https://github.com/gg-innovative/larafirebase/releases/tag/1.0.2, thanks!
